twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        company_name: 'White Lion'

when@test:
    twig:
        strict_variables: true