parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Twig\GlobalGendersExtension:
        arguments:
            $genderRepository: '@App\Repository\GenderRepository'
        tags: ['twig.extension']

    App\Twig\GlobalCartExtension:
        tags: ['twig.extension']
